services:
  # MySQL Database Service
  mysqldb:
    image: mysql:8.0
    container_name: ecommerce_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Maha@123
      MYSQL_DATABASE: jwt_auth
      MYSQL_USER: jwt_user
      MYSQL_PASSWORD: Maha@123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # NestJS Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: jwt_user
      DB_PASSWORD: Maha@123
      DB_NAME: jwt_auth
      JWT_SECRET: fallbackSecretKeyForDev
    depends_on:
      - mysqldb

  # React Frontend Service (Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecommerce_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
