ALTER USER 'root'@'localhost' IDENTIFIED BY 'Maha@123';
CREATE USER IF NOT EXISTS 'jwt_user'@'localhost' IDENTIFIED BY 'Maha@123';
CREATE USER IF NOT EXISTS 'jwt_user'@'%' IDENTIFIED BY 'Maha@123';
GRANT ALL PRIVILEGES ON *.* TO 'jwt_user'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'jwt_user'@'%' WITH GRANT OPTION;
CREATE DATABASE IF NOT EXISTS jwt_auth;
FLUSH PRIVILEGES;
